### ISSUE TITLE
Resources on deep learning

### ISSUE THREAD

**Issue by czyzby** [sekwiatkowski/komputation#8]
Might I ask which resources are you basing your library on? Are there any particular books or courses that you'd recommend? I feel like implementing some of the algorithms from scratch would give me a better understanding of deep learning, but I don't think rewriting code of the existing frameworks is the way to go.

Feel free to close this issue.

**Comment by sekwiatkowski** [comment]
Here are some of the resources that I found useful when I started to learn about machine learning:

1) [Andrew Ng's MOOC](https://www.coursera.org/learn/machine-learning)
2) [Yaser Abu-Mostafa's MOOC](https://work.caltech.edu/telecourse.html)
3) [Christopher Olah's blog posts](http://colah.github.io/about.html)
4) [Neural Networks and Deep Learning](http://neuralnetworksanddeeplearning.com/)
6) [Nano de Freitas' courses](https://www.youtube.com/user/ProfNandoDF/playlists)
5) Some of the publicly available Stanford on machine learning and neural network, e..g, [CS224n](http://web.stanford.edu/class/cs224n/) and [CS231n](http://cs231n.github.io/)

Also, keep in mind that I've used these resources several years ago. Newer material that is more relevant might have been published since then.

Implementing backpropagation for a simple neural network once might be a good use of time.
